
USE petstore;

DROP TABLE IF EXISTS PETSALE;
DROP TABLE IF EXISTS PET;


CREATE TABLE PETSALE (
    ID INTEGER NOT NULL,
    PET VARCHAR(20),
    SALEPRICE DECIMAL(6,2),
    PROFIT DECIMAL(6,2),
    SALEDATE DATE
);

CREATE TABLE PET (
    ID INTEGER NOT NULL,
    ANIMAL VARCHAR(20),
    QUANTITY INTEGER
);

INSERT INTO PETSALE (ID, PET, SALEPRICE, PROFIT, SALEDATE) VALUES
    (1, 'Cat', 450.09, 100.47, '2018-05-29'),
    (2, 'Dog', 666.66, 150.76, '2018-06-01'),
    (3, 'Parrot', 50.00, 8.90, '2018-06-04'),
    (4, 'Hamster', 60.60, 12.00, '2018-06-11'),
    (5, 'Goldfish', 48.48, 3.50, '2018-06-14');

INSERT INTO PET (ID, ANIMAL, QUANTITY) VALUES
    (1, 'Cat', 3),
    (2, 'Dog', 4),
    (3, 'Hamster', 2);

ALTER TABLE PETSALE ADD COLUMN QUANTITY INTEGER;
SELECT 'PETSALE after adding QUANTITY column:' AS status_update;
SELECT * FROM PETSALE;

UPDATE PETSALE ps JOIN PET p ON ps.PET = p.ANIMAL SET ps.QUANTITY = 1;
SELECT 'PETSALE after updating QUANTITY to 1 for each sale:' AS status_update;
SELECT * FROM PETSALE;



ALTER TABLE PETSALE DROP COLUMN PROFIT;
SELECT 'PETSALE after dropping PROFIT column:' AS status_update;
SELECT * FROM PETSALE;

ALTER TABLE PETSALE CHANGE COLUMN PET ANIMAL VARCHAR(20);
SELECT 'PETSALE after renaming PET to ANIMAL:' AS status_update;
SELECT * FROM PETSALE;


TRUNCATE TABLE PET;
SELECT 'PET table after TRUNCATE (structure remains, data is gone):' AS status_update;
SELECT * FROM PET;

DROP TABLE PET;
